CherchAppartBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CherchAppartBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '30'
            column: Name
        lastname:
            type: string
            length: '30'
            column: Lastname

        sexe:
             type: string
             length: '10'
             column: Sexe
    lifecycleCallbacks: {  }
