CherchAppartBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CherchAppartBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

    lifecycleCallbacks: {  }
