imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CherchAppartBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.profil_images: /uploads/images/profils

framework:
    #esi: ~
    translator: { fallbacks: fr }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: fr
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool: { type: memory }

# FosUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CherchAppartBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    service:
        mailer: fos_user.mailer.twig_swift
    profile:
        form:
            type: CherchAppartBundle\Form\ProfileType
    registration:
        form:
            type: CherchAppartBundle\Form\RegistrationType
        confirmation:
            enabled: false
            template:   '@FOSUser/Registration/email.txt.twig'
            from_email:
                address:        cherchappartnoreply@gmail.com
                sender_name:    cherchappartnoreply@gmail.com

# Hwioa Configuration
hwi_oauth:
    connect:
        confirmation: true
        registration_form: fos_user.registration.form.factory
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookID
    resource_owners:
        facebook:
            type: facebook
            client_id: 309194786265019
            client_secret: 63daeb2c51a41ff69dcb4146674e5d31

# EasyAdmin Configuration
easy_admin:
   # title: 'Cherch''Appart Admin'
    entities:
        Announce:
            class: CherchAppartBundle\Entity\Announce
        Announce_Informations:
            class: CherchAppartBundle\Entity\Announce_Informations
        Announce_Comments:
            class: CherchAppartBundle\Entity\Announce_Comments
        Announce_Fire:
            class: CherchAppartBundle\Entity\Announce_Fire
        Comments_Like:
            class: CherchAppartBundle\Entity\Comments_Like
        User:
            class: CherchAppartBundle\Entity\User
            list:
                fields: ['id',{ property: 'image', type: 'image', base_path: '%app.path.profil_images%'  }, 'name', 'lastname', 'sexe' ,'username', 'email', 'adress', 'postal_code', 'city', 'phone_number', 'enabled', 'lastLogin', 'confirmationToken', 'roles']
            show:
                fields: ['id',{ property: 'image', type: 'image', base_path: '%app.path.profil_images%'  }, 'Name', 'LastName', 'Sexe' ,'username', 'email', 'adress', 'Postal_Code', 'City', 'phone_number', 'enabled', 'lastLogin', 'confirmationToken', 'roles']
            form:
                fields: [{ property: 'imageFile', type: 'file' }, 'name', 'lastname', 'birthday', 'sexe' ,'username', 'password', 'email', 'adress', 'postal_code', 'city', 'phone_number', 'enabled', 'lastLogin', 'confirmationToken', 'roles']

#VichUploader Configuration
vich_uploader:
    db_driver: orm
    mappings:
        profil_images:
            uri_prefix:         '%app.path.profil_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/profils'

