# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_users:
            entity:
                class: CherchAppartBundle:User
                property: username
    encoders:
        CherchAppartBundle\Entity\User: plaintext
        #Symfony\Component\Security\Core\Blog\Blog: plaintext

       # role_hierarchy:
       #     ROLE_ADMIN: ROLE_UTILISATEUR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #Specific firewall for login       
        main_login:
            pattern: ^/($)
            anonymous: true
        main:
            pattern: ^/(home|myAccount|logout|login_check)
            anonymous: false
            form_login:
                login_path: /
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /home
            logout:
                invalidate_session: false
                path: /logout
                target: /
    access_control:

    acl:
        connection: default

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
