account:
    resource: "@CherchAppartBundle/Resources/config/routing/user.yml"
    prefix:   /myAccount

new_account:
    path:     /newAccount
    defaults: { _controller: "CherchAppartBundle:User:new" }
    methods:  [GET, POST]

home:
    path:    /home
    defaults: { _controller: CherchAppartBundle:cherchAppart:index }
login:
    path:    /
    defaults: { _controller: CherchAppartBundle:Security:login }
#Page d'accès d'authentification

login_check:
    path:    /login_check

logout:
    path:    /logout
