account:
    resource: "@CherchAppartBundle/Resources/config/routing/user.yml"
    prefix:   /account

home:
    path:    /home
    defaults: { _controller: CherchAppartBundle:cherchAppart:index }
login:
    path:    /login
    defaults: { _controller: CherchAppartBundle:Security:login }
#Page d'accès d'authentification

login_check:
    path:    /login_check

logout:
    path:    /logout
