home:
    path:    /
    defaults: { _controller: CherchAppartBundle:Contents\Home:index }

profil:
    resource: "@CherchAppartBundle/Resources/config/routing/profil.yml"
    prefix:   /

announce:
    resource: "@CherchAppartBundle/Resources/config/routing/announce.yml"
    prefix:   /announce

contact:
    path:  /contact
    defaults: { _controller: CherchAppartBundle:Contents\Contact:index }
    methods:  [GET, POST]

logout:
    path:  /logout
