cherch_appart_homepage:
    path:     /
    defaults: { _controller: CherchAppartBundle:Default:index }
#Homepaage sans sans authentification

cherch_appart_homepage_logged:
    path:     /home
    defaults: { _controller: CherchAppartBundle:cherchAppart:index }
#Homepaage sans sans authentification

login:
    path:    /login
    defaults: { _controller: CherchAppartBundle:Security:login }
#Page d'accès d'authentification

login_check:
    path:    /login_check

logout:
    path:    /logout
