<?php

namespace CherchAppartBundle\Repository;

/**
 * Announce_FireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Announce_FireRepository extends \Doctrine\ORM\EntityRepository
{
}
