<?php

namespace CherchAppartBundle\Repository;

/**
 * AnnounceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnounceRepository extends \Doctrine\ORM\EntityRepository
{
}
