<?php

namespace CherchAppartBundle\Repository;

/**
 * Announce_InformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Announce_InformationsRepository extends \Doctrine\ORM\EntityRepository
{
}
