<?php

namespace CherchAppartBundle\Repository;

/**
 * Comments_likeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comments_likeRepository extends \Doctrine\ORM\EntityRepository
{
}
